language: rust

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - libssl-dev
    - os: windows

    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.35.0

cache: cargo

before_cache: |
  rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  if [[ "$TRAVIS_RUST_VERSION" == beta && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo install cargo-tarpaulin -f
  fi

script:
  - cargo test --verbose
  - cargo test --all-features --verbose
  - cargo test --features "serde1" --verbose
  - cargo test --features "bigint" --verbose
  - cargo test --features "bigdecimal" --verbose
  - cargo test --features "chrono" --verbose
  - cargo test --features "regex" --verbose

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == beta && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo tarpaulin --out Xml --all-features --ignore-tests --verbose
    bash <(curl -s https://codecov.io/bash)
  fi
